name: ohmypet_res
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_cropper: ^3.0.1
  cupertino_icons: ^1.0.2
  
  image_picker: ^0.8.7     # A침adir Fotografia de la mascota
  
  flutter_native_splash: ^2.2.19 # Crear Pantalla Splash
  
  firebase_core: ^2.8.0 # Implementaci칩n de Firebase
  firebase_auth: ^4.3.0 # Complemento de Autentificaci칩n de Firebase
  
  google_sign_in: ^6.0.2 # Logueo mediante una cuenta de Google
  flutter_facebook_auth: ^5.0.8 # Logueo mediante Facebook
  
  sqflite: ^2.2.6 # Implementaci칩n de SQLite
  
  pdf: ^3.10.1 # Creacion de archivos PDF 
  path_provider: ^2.0.14
  printing: ^5.10.3 # Vista previa del documento PDF
  open_file_plus: ^3.4.0 # Abrir Documento

  provider: ^6.0.5 #Mover informacion dentro del documento

  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mask_text_input_formatter: ^2.4.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/logos/
    - assets/icons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Italic.ttf
        - asset: fonts/OpenSans-Bold.ttf
  #          
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
